name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH into DigitalOcean VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_SECRET_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd var/www/buybyraffle/buybyraffle-web-app-new
          git pull origin main
          sudo systemctl restart apache2
